/**
 *
 *  RobotMaps.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "RobotMaps.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::robotdb;

const std::string RobotMaps::Cols::_id = "\"id\"";
const std::string RobotMaps::Cols::_name = "\"name\"";
const std::string RobotMaps::Cols::_x = "\"x\"";
const std::string RobotMaps::Cols::_y = "\"y\"";
const std::string RobotMaps::Cols::_theta = "\"theta\"";
const std::string RobotMaps::Cols::_image = "\"image\"";
const std::string RobotMaps::Cols::_modifytime = "\"modifytime\"";
const std::string RobotMaps::Cols::_pbstream = "\"pbstream\"";
const std::string RobotMaps::primaryKeyName = "id";
const bool RobotMaps::hasPrimaryKey = true;
const std::string RobotMaps::tableName = "\"robot_maps\"";

const std::vector<typename RobotMaps::MetaData> RobotMaps::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"name","std::string","text",0,0,0,1},
{"x","double","double precision",8,0,0,0},
{"y","double","double precision",8,0,0,0},
{"theta","double","double precision",8,0,0,0},
{"image","std::string","text",0,0,0,1},
{"modifytime","std::string","text",0,0,0,1},
{"pbstream","std::vector<char>","bytea",0,0,0,0}
};
const std::string &RobotMaps::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
RobotMaps::RobotMaps(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["x"].isNull())
        {
            x_=std::make_shared<double>(r["x"].as<double>());
        }
        if(!r["y"].isNull())
        {
            y_=std::make_shared<double>(r["y"].as<double>());
        }
        if(!r["theta"].isNull())
        {
            theta_=std::make_shared<double>(r["theta"].as<double>());
        }
        if(!r["image"].isNull())
        {
            image_=std::make_shared<std::string>(r["image"].as<std::string>());
        }
        if(!r["modifytime"].isNull())
        {
            modifytime_=std::make_shared<std::string>(r["modifytime"].as<std::string>());
        }
        if(!r["pbstream"].isNull())
        {
            auto str = r["pbstream"].as<std::string_view>();
            if(str.length()>=2&&
                str[0]=='\\'&&str[1]=='x')
            {
                pbstream_=std::make_shared<std::vector<char>>(drogon::utils::hexToBinaryVector(str.data()+2,str.length()-2));
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            x_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            y_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            theta_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            image_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            modifytime_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto str = r[index].as<std::string_view>();
            if(str.length()>=2&&
                str[0]=='\\'&&str[1]=='x')
            {
                pbstream_=std::make_shared<std::vector<char>>(drogon::utils::hexToBinaryVector(str.data()+2,str.length()-2));
            }
        }
    }

}

RobotMaps::RobotMaps(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            x_=std::make_shared<double>(pJson[pMasqueradingVector[2]].asDouble());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            y_=std::make_shared<double>(pJson[pMasqueradingVector[3]].asDouble());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            theta_=std::make_shared<double>(pJson[pMasqueradingVector[4]].asDouble());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            image_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            modifytime_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto str = pJson[pMasqueradingVector[7]].asString();
            pbstream_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
}

RobotMaps::RobotMaps(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("x"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["x"].isNull())
        {
            x_=std::make_shared<double>(pJson["x"].asDouble());
        }
    }
    if(pJson.isMember("y"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["y"].isNull())
        {
            y_=std::make_shared<double>(pJson["y"].asDouble());
        }
    }
    if(pJson.isMember("theta"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["theta"].isNull())
        {
            theta_=std::make_shared<double>(pJson["theta"].asDouble());
        }
    }
    if(pJson.isMember("image"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["image"].isNull())
        {
            image_=std::make_shared<std::string>(pJson["image"].asString());
        }
    }
    if(pJson.isMember("modifytime"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["modifytime"].isNull())
        {
            modifytime_=std::make_shared<std::string>(pJson["modifytime"].asString());
        }
    }
    if(pJson.isMember("pbstream"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["pbstream"].isNull())
        {
            auto str = pJson["pbstream"].asString();
            pbstream_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
}

void RobotMaps::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            x_=std::make_shared<double>(pJson[pMasqueradingVector[2]].asDouble());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            y_=std::make_shared<double>(pJson[pMasqueradingVector[3]].asDouble());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            theta_=std::make_shared<double>(pJson[pMasqueradingVector[4]].asDouble());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            image_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            modifytime_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto str = pJson[pMasqueradingVector[7]].asString();
            pbstream_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
}

void RobotMaps::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("x"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["x"].isNull())
        {
            x_=std::make_shared<double>(pJson["x"].asDouble());
        }
    }
    if(pJson.isMember("y"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["y"].isNull())
        {
            y_=std::make_shared<double>(pJson["y"].asDouble());
        }
    }
    if(pJson.isMember("theta"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["theta"].isNull())
        {
            theta_=std::make_shared<double>(pJson["theta"].asDouble());
        }
    }
    if(pJson.isMember("image"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["image"].isNull())
        {
            image_=std::make_shared<std::string>(pJson["image"].asString());
        }
    }
    if(pJson.isMember("modifytime"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["modifytime"].isNull())
        {
            modifytime_=std::make_shared<std::string>(pJson["modifytime"].asString());
        }
    }
    if(pJson.isMember("pbstream"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["pbstream"].isNull())
        {
            auto str = pJson["pbstream"].asString();
            pbstream_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
}

const int32_t &RobotMaps::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &RobotMaps::getId() const noexcept
{
    return id_;
}
void RobotMaps::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename RobotMaps::PrimaryKeyType & RobotMaps::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &RobotMaps::getValueOfName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &RobotMaps::getName() const noexcept
{
    return name_;
}
void RobotMaps::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[1] = true;
}
void RobotMaps::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[1] = true;
}

const double &RobotMaps::getValueOfX() const noexcept
{
    static const double defaultValue = double();
    if(x_)
        return *x_;
    return defaultValue;
}
const std::shared_ptr<double> &RobotMaps::getX() const noexcept
{
    return x_;
}
void RobotMaps::setX(const double &pX) noexcept
{
    x_ = std::make_shared<double>(pX);
    dirtyFlag_[2] = true;
}
void RobotMaps::setXToNull() noexcept
{
    x_.reset();
    dirtyFlag_[2] = true;
}

const double &RobotMaps::getValueOfY() const noexcept
{
    static const double defaultValue = double();
    if(y_)
        return *y_;
    return defaultValue;
}
const std::shared_ptr<double> &RobotMaps::getY() const noexcept
{
    return y_;
}
void RobotMaps::setY(const double &pY) noexcept
{
    y_ = std::make_shared<double>(pY);
    dirtyFlag_[3] = true;
}
void RobotMaps::setYToNull() noexcept
{
    y_.reset();
    dirtyFlag_[3] = true;
}

const double &RobotMaps::getValueOfTheta() const noexcept
{
    static const double defaultValue = double();
    if(theta_)
        return *theta_;
    return defaultValue;
}
const std::shared_ptr<double> &RobotMaps::getTheta() const noexcept
{
    return theta_;
}
void RobotMaps::setTheta(const double &pTheta) noexcept
{
    theta_ = std::make_shared<double>(pTheta);
    dirtyFlag_[4] = true;
}
void RobotMaps::setThetaToNull() noexcept
{
    theta_.reset();
    dirtyFlag_[4] = true;
}

const std::string &RobotMaps::getValueOfImage() const noexcept
{
    static const std::string defaultValue = std::string();
    if(image_)
        return *image_;
    return defaultValue;
}
const std::shared_ptr<std::string> &RobotMaps::getImage() const noexcept
{
    return image_;
}
void RobotMaps::setImage(const std::string &pImage) noexcept
{
    image_ = std::make_shared<std::string>(pImage);
    dirtyFlag_[5] = true;
}
void RobotMaps::setImage(std::string &&pImage) noexcept
{
    image_ = std::make_shared<std::string>(std::move(pImage));
    dirtyFlag_[5] = true;
}

const std::string &RobotMaps::getValueOfModifytime() const noexcept
{
    static const std::string defaultValue = std::string();
    if(modifytime_)
        return *modifytime_;
    return defaultValue;
}
const std::shared_ptr<std::string> &RobotMaps::getModifytime() const noexcept
{
    return modifytime_;
}
void RobotMaps::setModifytime(const std::string &pModifytime) noexcept
{
    modifytime_ = std::make_shared<std::string>(pModifytime);
    dirtyFlag_[6] = true;
}
void RobotMaps::setModifytime(std::string &&pModifytime) noexcept
{
    modifytime_ = std::make_shared<std::string>(std::move(pModifytime));
    dirtyFlag_[6] = true;
}

const std::vector<char> &RobotMaps::getValueOfPbstream() const noexcept
{
    static const std::vector<char> defaultValue = std::vector<char>();
    if(pbstream_)
        return *pbstream_;
    return defaultValue;
}
std::string RobotMaps::getValueOfPbstreamAsString() const noexcept
{
    static const std::string defaultValue = std::string();
    if(pbstream_)
        return std::string(pbstream_->data(),pbstream_->size());
    return defaultValue;
}
const std::shared_ptr<std::vector<char>> &RobotMaps::getPbstream() const noexcept
{
    return pbstream_;
}
void RobotMaps::setPbstream(const std::vector<char> &pPbstream) noexcept
{
    pbstream_ = std::make_shared<std::vector<char>>(pPbstream);
    dirtyFlag_[7] = true;
}
void RobotMaps::setPbstream(const std::string &pPbstream) noexcept
{
    pbstream_ = std::make_shared<std::vector<char>>(pPbstream.c_str(),pPbstream.c_str()+pPbstream.length());
    dirtyFlag_[7] = true;
}
void RobotMaps::setPbstreamToNull() noexcept
{
    pbstream_.reset();
    dirtyFlag_[7] = true;
}

void RobotMaps::updateId(const uint64_t id)
{
}

const std::vector<std::string> &RobotMaps::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "name",
        "x",
        "y",
        "theta",
        "image",
        "modifytime",
        "pbstream"
    };
    return inCols;
}

void RobotMaps::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getX())
        {
            binder << getValueOfX();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getY())
        {
            binder << getValueOfY();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTheta())
        {
            binder << getValueOfTheta();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getImage())
        {
            binder << getValueOfImage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getModifytime())
        {
            binder << getValueOfModifytime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getPbstream())
        {
            binder << getValueOfPbstream();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> RobotMaps::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void RobotMaps::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getX())
        {
            binder << getValueOfX();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getY())
        {
            binder << getValueOfY();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTheta())
        {
            binder << getValueOfTheta();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getImage())
        {
            binder << getValueOfImage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getModifytime())
        {
            binder << getValueOfModifytime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getPbstream())
        {
            binder << getValueOfPbstream();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value RobotMaps::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getX())
    {
        ret["x"]=getValueOfX();
    }
    else
    {
        ret["x"]=Json::Value();
    }
    if(getY())
    {
        ret["y"]=getValueOfY();
    }
    else
    {
        ret["y"]=Json::Value();
    }
    if(getTheta())
    {
        ret["theta"]=getValueOfTheta();
    }
    else
    {
        ret["theta"]=Json::Value();
    }
    if(getImage())
    {
        ret["image"]=getValueOfImage();
    }
    else
    {
        ret["image"]=Json::Value();
    }
    if(getModifytime())
    {
        ret["modifytime"]=getValueOfModifytime();
    }
    else
    {
        ret["modifytime"]=Json::Value();
    }
    if(getPbstream())
    {
        ret["pbstream"]=drogon::utils::base64Encode((const unsigned char *)getPbstream()->data(),getPbstream()->size());
    }
    else
    {
        ret["pbstream"]=Json::Value();
    }
    return ret;
}

std::string RobotMaps::toString() const
{
    return toJson().toStyledString();
}

Json::Value RobotMaps::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[1]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getX())
            {
                ret[pMasqueradingVector[2]]=getValueOfX();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getY())
            {
                ret[pMasqueradingVector[3]]=getValueOfY();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getTheta())
            {
                ret[pMasqueradingVector[4]]=getValueOfTheta();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getImage())
            {
                ret[pMasqueradingVector[5]]=getValueOfImage();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getModifytime())
            {
                ret[pMasqueradingVector[6]]=getValueOfModifytime();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getPbstream())
            {
                ret[pMasqueradingVector[7]]=drogon::utils::base64Encode((const unsigned char *)getPbstream()->data(),getPbstream()->size());
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getX())
    {
        ret["x"]=getValueOfX();
    }
    else
    {
        ret["x"]=Json::Value();
    }
    if(getY())
    {
        ret["y"]=getValueOfY();
    }
    else
    {
        ret["y"]=Json::Value();
    }
    if(getTheta())
    {
        ret["theta"]=getValueOfTheta();
    }
    else
    {
        ret["theta"]=Json::Value();
    }
    if(getImage())
    {
        ret["image"]=getValueOfImage();
    }
    else
    {
        ret["image"]=Json::Value();
    }
    if(getModifytime())
    {
        ret["modifytime"]=getValueOfModifytime();
    }
    else
    {
        ret["modifytime"]=Json::Value();
    }
    if(getPbstream())
    {
        ret["pbstream"]=drogon::utils::base64Encode((const unsigned char *)getPbstream()->data(),getPbstream()->size());
    }
    else
    {
        ret["pbstream"]=Json::Value();
    }
    return ret;
}

bool RobotMaps::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, true))
            return false;
    }
    else
    {
        err="The name column cannot be null";
        return false;
    }
    if(pJson.isMember("x"))
    {
        if(!validJsonOfField(2, "x", pJson["x"], err, true))
            return false;
    }
    if(pJson.isMember("y"))
    {
        if(!validJsonOfField(3, "y", pJson["y"], err, true))
            return false;
    }
    if(pJson.isMember("theta"))
    {
        if(!validJsonOfField(4, "theta", pJson["theta"], err, true))
            return false;
    }
    if(pJson.isMember("image"))
    {
        if(!validJsonOfField(5, "image", pJson["image"], err, true))
            return false;
    }
    else
    {
        err="The image column cannot be null";
        return false;
    }
    if(pJson.isMember("modifytime"))
    {
        if(!validJsonOfField(6, "modifytime", pJson["modifytime"], err, true))
            return false;
    }
    else
    {
        err="The modifytime column cannot be null";
        return false;
    }
    if(pJson.isMember("pbstream"))
    {
        if(!validJsonOfField(7, "pbstream", pJson["pbstream"], err, true))
            return false;
    }
    return true;
}
bool RobotMaps::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool RobotMaps::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("x"))
    {
        if(!validJsonOfField(2, "x", pJson["x"], err, false))
            return false;
    }
    if(pJson.isMember("y"))
    {
        if(!validJsonOfField(3, "y", pJson["y"], err, false))
            return false;
    }
    if(pJson.isMember("theta"))
    {
        if(!validJsonOfField(4, "theta", pJson["theta"], err, false))
            return false;
    }
    if(pJson.isMember("image"))
    {
        if(!validJsonOfField(5, "image", pJson["image"], err, false))
            return false;
    }
    if(pJson.isMember("modifytime"))
    {
        if(!validJsonOfField(6, "modifytime", pJson["modifytime"], err, false))
            return false;
    }
    if(pJson.isMember("pbstream"))
    {
        if(!validJsonOfField(7, "pbstream", pJson["pbstream"], err, false))
            return false;
    }
    return true;
}
bool RobotMaps::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool RobotMaps::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
